- hosts: main
  tasks:
    - name: Install ubuntu packages
      become: true
      apt:
        name:
            - htop
            - nfs-common
            - net-tools

    - name: Install pip packages
      pip:
        name:
          - pywinrm
          - jsondiff

- hosts: master,managers
  tasks:
    - name: Install ubuntu packages
      become: true
      apt:
        name:
            - auditd
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg2
            - software-properties-common
            - htop
            - net-tools
            - nfs-common
            - ntp
            - python3-dev
            - python3-pip
            - python3-venv
            - python-dev
            - python-pip
            - python-setuptools
            - virtualenv
            - s3fs
            - sysvbanner
            - zsh
        state: latest
        update_cache: yes


    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable


    - name: Install Docker CE
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        update_cache: yes

    - name: Install docker-compose & ansible
      pip:
        name:
          - jsondiff
          - docker-compose
          - ansible

    - name: Usermod docker
      shell: usermod -aG docker exorcito
      become: true


- hosts: master
    - name: Install NFS Server
      apt:
        - name:
              - nfs-server
      state: latest

    - name: Verify export /share
      shell: grep "^/share" /etc/exports
      register: test_export_data
      ignore_errors: yes

    - name: Add export /share
      lineinfile:
        dest: /etc/exports
        line: "/share mustafar2.sw.com(rw,sync,no_subtree_check) mustafar3.sw.com(rw,sync,no_subtree_check) bakura.sw.com(rw,sync,no_subtree_check)"
      when: test_export_data != ""

    - name: Refresh export
      shell: exportfs -a
      become: true


- hosts: ansible,managers            
    - name: Verify share NFS
      shell: grep "^mustafar1.sw.com:/share" /etc/fstab
      register: test_fstab_data
      ignore_errors: yes
    
    - debug: msg="{{test_fstab_data.stdout}}"

    - name: Add share to fstab
      lineinfile:
        dest: /etc/fstab
        line: "mustafar1.sw.com:/share /share nfs x-systemd.automount,rw,nolock 0 0"
      become: true        
      register: fstab
      when: test_fstab_data != ""           

    - name: Mount /share
      shell: mount /share
      become: true      
