- hosts: master,managers
  roles:
    - ubuntu

- hosts: ansible,master,managers
  roles:
    - zsh

- hosts: ansible
  roles:
    - awx
    - nfs-server

- hosts: master,managers
  roles:
    - nfs-client
