- hosts: awx,masters,workers
  roles:
    - ubuntu

- hosts: awx,masters,workers
  roles:
    - zsh

- hosts: awx
  roles:
    - awx

- hosts: awx,masters,workers
  roles:
    - nfs-client

- hosts: wsl
  become: true
  vars:
    awscli_user: exorcito
    awscli_user_home_dir: /home/exorcito
  roles:
    - andrewrothstein.terraform
    - singleplatform-eng.awscli
    - andrewrothstein.kubectl
    - andrewrothstein.kubernetes-helm