    - name: Install ubuntu packages in ansible-controller
      become: true
      apt:
        name:
            - autojump
            - zsh
            - zsh-antigen
            - zsh-syntax-highlighting
            - git
            - zsh-autosuggestions
            - colorize

    - name: Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: stat_rc_result
    
    - name: Check if .oh-my-zsh exists
      stat:
        path: ~/.oh-my-zsh
      register: stat_oh_my_zsh_result
    
    - name: Cloning oh-my-zsh repo from git
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh
        dest=~/.oh-my-zsh

    - name: Cloning theme Powerline10K
      git:
        repo=https://github.com/romkatv/powerlevel10k.git
        dest=~/.oh-my-zsh/custom/themes/powerlevel10k  

    - name: Install plugin ZSH - completions
      git:
        repo=git://github.com/zsh-users/zsh-completions.git
        dest=~/.oh-my-zsh/custom/plugins/zsh-completions
  
    - name: Install plugin ZSH - suggestions
      git:
        repo=https://github.com/zsh-users/zsh-autosuggestions
        dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions          

    - name: Install plugin ZSH - syntax-highlighting
      git:
        repo=https://github.com/zsh-users/zsh-syntax-highlighting
        dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Define default shell ZSH
      become: true
      shell: chsh exorcito -s /usr/bin/zsh
  
    - name: Cloning custom .zshrc file from git
      git:
        repo=https://github.com/exorcito/dotfiles.git
        dest=~/dotfiles
        force=yes
  
    - name: Delete ZSH profile
      file:
        path: ~/.zshrc
        state: absent
  
    - name: Install ZSH profile
      copy:
        src: ~/dotfiles/.zshrc 
        dest: ~/.zshrc

    - name: Install Powerline config
      copy:
        src: ~/dotfiles/.p10k.zsh 
        dest: ~/.p10k.zsh