- name: Install ubuntu packages in machines
  become: true
  apt:
    name:
      - htop
      - net-tools
      - auditd
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - ntp
      - python3-dev
      - python3-pip
      - python3-venv
      - python-dev
      - python-pip
      - python-setuptools
      - virtualenv
      - s3fs
      - sysvbanner

- name: Install pip packages in machines
  become: true
  pip:
    name:
      - jsondiff      