- name: Install ubuntu packages in ansible-controller
  become: true
  apt:
    name:
      - nfs-common

- name: Verify share NFS
  shell: grep "^192.168.0.150:/volume1/backups/VMS:/share" /etc/fstab
  register: test_fstab_data
  ignore_errors: yes

- name: Add share to fstab
  lineinfile:
    dest: /etc/fstab
    line: "192.168.0.150:/volume1/backups/VMS /share nfs x-systemd.automount,rw,nolock 0 0"
  become: true        
  register: fstab
  when: test_fstab_data != ""           

- name: Verify /share
  file:
    path: /share
    state: directory
  become: true

- name: Mount /share
  shell: mount /share
  become: true