- name: Install NFS Server
  apt:
    name: 
      - nfs-server
    update_cache: yes
  become: true

- name: Verify exports
  stat:
    path: /etc/exports
  register: exports_file

- name: Create file exports if not exists
  file:
    path: /etc/exports
    state: touch
  when: exports_file.stat.exists == True
  become: true

- name: Verify export /share
  shell: grep "^/share" /etc/exports
  register: test_export_data
  ignore_errors: yes

- name: Add export /share
  lineinfile:
    dest: /etc/exports
    line: "/share *(rw,sync,no_subtree_check)"
  when: test_export_data != ""
  become: true

- name: Refresh export
  shell: exportfs -a
  become: true
